### ISSUE TITLE
POST /{registration_endpoint_path} request body is JSON

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-authorization#113]
This note is incorrect:

https://github.com/AMWA-TV/is-10/blob/518b4532225ff5503169903409c98db6c8bd294b/APIs/AuthorizationAPI.raml#L166-L167

Other request bodies in this API are application/x-www-form-urlencoded but this one isn't.

**Comment by lo-simon** [comment]
Yes, I think it is incorrect. The `content-type` should be `application/json`, we can remove the `Note`.

**Comment by peterbrightwell** [comment]
Architecture Review Group review: place on backlog
