### ISSUE TITLE
x-nmos-api

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-authorization#20]
token_schema doesn't look quite right?

This pattern matches a single character:

https://github.com/AMWA-TV/nmos-authorization/blob/0db57ebc1a7465091d4579fa47579e6960c71f22/APIs/schemas/token_schema.json#L43

And could the read and write sub props of that be done just as normal properties?

It'd be nice to have an example for this schema in the examples folder too.

**Comment by prince-chrismc** [comment]
You got me wondering how my test code was passing =?
The regex is also missing the start and top characters.

For my token,
```json
{
  "aud": [
    "*"
  ],
  "client_id": "dNgeZP6oAf6JoJREHkpl9IqjO_KyIWlu",
  "exp": 1585488915,
  "iat": 1585488555,
  "iss": "proto://mock_auth_server.vpg.test",
  "sub": "c0",
  "x-nmos-api": {
    "registration": {
      "read": [
        "*"
      ],
      "write": [
        "*"
      ]
    }
  }
}
```

It passes with the current schema because there is no `"additionalProperties": false`

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "JSON Web Token Contents",
  "description": "Claims contained within JSON Web Token",
  "type": "object",
  "properties": {
    "iss": {
      "description": "The DNS name of the Authorization Server issuing the token",
      "type": "string",
      "format": "uri"
    },
    "sub": {
      "description": "The unique identifier assigned to the end-user by the user authorization system",
      "type": "string"
    },
    "aud": {
      "description": "The fully qualified domain name of the intended recipient (Resource Server), or a domain name containing wild-card characters",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "exp": {
      "description": "The UTC time at which the token expires",
      "type": "number"
    },
    "iat": {
      "description": "The UTC time at which the token was issued",
      "type": "number"
    },
    "client_id": {
      "description": "The client identifier of the OAuth 2.0 client that requested the token",
      "type": "string"
    },
    "scope": {
      "description": "A string containing a space-separated list of scopes associated with the token",
      "type": "string"
    },
    "x-nmos-api": {
      "additionalProperties": false,
      "description": "An object containing the access permissions of the user for the listed NMOS APIs",
      "type": "object",
      "patternProperties": {
        "^[a-z_-]+$": {
  	  	"additionalProperties": false,
          "type": "object",
          "minProperties": 1,
          "patternProperties": {
            "^read$|^write$": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1
            }
          }
        }
      }
    }
  },
  "required": [
    "iss",
    "sub",
    "aud",
    "exp",
    "client_id",
    "x-nmos-api"
  ]
}
```

Correctly fails

```json
{
  "aud": [
    "*"
  ],
  "client_id": "dNgeZP6oAf6JoJREHkpl9IqjO_KyIWlu",
  "exp": 1585488915,
  "iat": 1585488555,
  "iss": "proto://mock_auth_server.vpg.test",
  "sub": "c0",
  "x-nmos-api": {
    "regist&ration": {
      "read": [
        "*"
      ],
      "write": [
        "*"
      ]
    }
  }
}
```

And

```json
{
  "aud": [
    "*"
  ],
  "client_id": "dNgeZP6oAf6JoJREHkpl9IqjO_KyIWlu",
  "exp": 1585488915,
  "iat": 1585488555,
  "iss": "proto://mock_auth_server.vpg.test",
  "sub": "c0",
  "x-nmos-api": {
    "registration": {
      "paint": [
        "*"
      ],
      "write": [
        "*"
      ]
    }
  }
}
```

While passing the original one

**Comment by prince-chrismc** [comment]
> And could the read and write sub props of that be done just as normal properties?

I am indifferent for which is "best" but the follow does work.

```json
          "properties": {
            "read": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1
            },
              "write": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1
            }
          }
```

**Comment by garethsb** [comment]
The docs talk about specs being able to define other **permissions** than `"read"` and `"write"` so this may need refactoring anyway? This new register also needs adding to the NMOS Parameter Registers.

**Comment by garethsb** [comment]
Would it be useful to constrain the value of the access permission array elements to match a URL path (plus un-percent-encoded `*` as the wildcard) as per the docs?

Given the way the docs currently define this (to begin after the absolute path `/x-nmos/{api_name}/{version}/` in the case of NMOS APIs), none of the [RFC 3986 Path productions](https://tools.ietf.org/html/rfc3986#section-3.3) are quite appropriate as a starting point. The `path-rootless` one is close, but I assume we're allowing `""`, empty string, to indicate the user has the permission for the whole API?

**Comment by garethsb** [comment]
Actually, although examples have only shown the `*` wildcard, the docs refer to [POSIX Pattern Matching Notation](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_13) which seems a little problematic to me, since it brings in an alternative regex form, etc. If we want that level of flexibility why not just make the string a JSON Schema regex?

**Comment by dannymeloy** [comment]
I think we stuck with pattern-matching as it was seen as simpler than regex, with regards to human-readability (it's expected that machine parsing is trivial either way.) I think use of wildcards, specifically asterisk-syntax, was the predominant, if not the only, use-case we had in mind. Perhaps this needs to be limited in the spec? 

I see no reason why we can't just define the `read` and `write` properties explicitly, as demonstrated by Chris above, and by _not _specifying the `additionalProperties` tag that opens the door for any additional access permissions that may need to be defined in the future?

WRT defining the access permissions array in the schema, this can be done if people think it would aid the construction of token claims. The empty string (`""`) shouldn't be allowed and this should likely be defined in the spec also. To indicate access to the whole API, a single asterisk (`*`) should be used, as in the examples.

Hopefully this makes sense. Ultimately readability was at the forefront of our minds WRT token contents.

**Comment by garethsb** [comment]
Hmm, the spec refers to POSIX Pattern Matching which includes a regex form as well as `*` and `?`?

So `*` can match any number of path segments?

**Comment by dannymeloy** [comment]
Yeah, this should allow the path segment to be fed into off-the-shelf parsers, and simplifies the substitution of the ends of valid paths

**Comment by prince-chrismc** [comment]
> The docs talk about specs being able to define other **permissions** than `"read"` and `"write"` so this may need refactoring anyway? This new register also needs adding to the NMOS Parameter Registers.

I had to double back and reread 4.4 I had not absorb that yet.

as for the pattern match, I like the idea of it being constrained to the `*`. This is was the use case we all had in mind, it will be expressive enough to meet all use cases

**Comment by garethsb** [comment]
> Yeah, this should allow the path segment to be fed into off-the-shelf parsers, and simplifies the substitution of the ends of valid paths

I am dubious about this argument. Any NMOS implementation with JSON Schema validation is going to have access to a ECMA 262 regex parser, and for URL route matching, whatever library they use for that - also ECMA regex in our case, but e.g. [Express.js routing](https://expressjs.com/en/guide/routing.html) uses [path-to-regexp](https://www.npmjs.com/package/path-to-regexp) which has a different style altogether. Doesn't it seem quite unlikely that anyone will directly use POSIX pattern matching?

If we want a simplified form, e.g. just supporting `*` for one (or any number) of path-segments (I think I saw `/single/*/transportfile` or something similar with a `*` in the middle as well as at the end, right?), and maybe `?` for single character matches within a path-segment (i.e. only matching path-segment charaters, especially not the `/` character), perhaps we could just specify that?

**Comment by dannymeloy** [comment]
Yes perhaps my means / reasoning was incorrect but the ends should hopefully be the same - minimizing the range of syntax used in order to simplistically demonstrate path identifiers.

**Comment by prince-chrismc** [comment]
Perhaps a good topic to revisit during Thursdays call.

Having small easy to read tokens was the primary motivation. Perhaps using standard regex provides the most flexiblity for the lowest cost. I have not seen any strong objects to regex.

**Comment by garethsb** [comment]
Your proposal to just support `*` would be very simple, especially as other URI path-segment characters wouldn't need escaping, as they might if we went for full regex (haven't checked all regex chars against URL sub-delims, yet).

If this spec only allowed `*` would that be sufficiently expressive? Would it match exactly one, or zero-or-more, whole path-segments, or would it just match any number of path characters? Any of those could mechanically be turned into a regex, while keeping the token size down.

**Comment by dannymeloy** [comment]
The current thinking is that the `*` would match any number of path characters - so a single asterisk could correspond to as many segments as you wished

**Comment by prince-chrismc** [comment]
I had not expected that `/single/*/transportfile` would be a use case, I was always under the impression that `*` was a suffix to remaining path segments.

**Comment by prince-chrismc** [comment]
Would `"single/*` permit the path `"http://192.168.66.166:8080/x-nmos/connection/v1.1/single"`

**Comment by garethsb** [comment]
> Would `"single/*` permit the path `"http://192.168.66.166:8080/x-nmos/connection/v1.1/single"`

In my view, no. It would allow `"http://192.168.66.166:8080/x-nmos/connection/v1.1/single/"` with the trailing slash. If a client should be permitted to access the URL without the trailing slash the **x-nmos-api** claim would have to be `"single*"`.

More concerning should be what would happen with a request to `/x-nmos/connection/v1.1/single/../bulk`? I'm not sure that we require API implementations to support dot segments, but for those that do, we seem to need some words that require the match to be done after _appropriate_ [URL normalization](https://en.wikipedia.org/wiki/URI_normalization#Normalizations_that_preserve_semantics).

**Comment by andrewbonney** [comment]
> More concerning should be what would happen with a request to `/x-nmos/connection/v1.1/single/../bulk`? I'm not sure that we require API implementations to support dot segments, but for those that do, we seem to need some words that require the match to be done after _appropriate_ [URL normalization](https://en.wikipedia.org/wiki/URI_normalization#Normalizations_that_preserve_semantics).

That seems to link through to RFC 3986 which has some useful sections we could reference. Specifically https://tools.ietf.org/html/rfc3986#section-6.2.2.3 covers the dot notation. Unless we need to consider percent encoding as well (I can't immediately think of a use case) then it may be sufficient to require processing paths as-per https://tools.ietf.org/html/rfc3986#section-5.2.4 or equivalent before comparing with the claims.

**Comment by NEOAdvancedTechnology** [comment]
Conclusion: * = zero or more of any allowed URL characters including "/", i.e. a regex ".*" <- Is @garethsb-sony OK with this???

"." ".." in relative URLs:  normalization to absolute URLs prior to comparison required <- this will likely require a PR to documentation

**Comment by garethsb** [comment]
> Conclusion: * = zero or more of any allowed URL characters including "/", i.e. a regex ".*" <- Is @garethsb-sony OK with this???

:-) PR #22 is good. 

> "." ".." in relative URLs: normalization to absolute URLs prior to comparison required <- this will likely require a PR to documentation

I agree with @andrewbonney that we can probably refer to sections of RFC 3986. We just need to be careful to require enough to avoid a security hole (like `"single/senders/*"` matching `"single/senders/../receivers/etc."`) without being overly prescriptive or mandating normalizations that are not always valid (as the wiki page and RFC discuss).
