### ISSUE TITLE
Claim to scope mapping simplification

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-authorization#26]
At present we have scopes like `registration`, `connection` etc, which map into a claim structure under `x-nmos-api`. Whilst it's certainly possible to create this mapping in commercial auth servers, it appears as though something like the following would be simpler. It would be worth considering a different pattern to potentially ease deployments.

**Scope Name**: `registration`
**Resultant Claim**: `"x-nmos-registration": {...}`

**Scope Name**: `connection`
**Resultant Claim**: `"x-nmos-connection": {...}`

It may equally be possible to drop the `x-nmos` from the claim name, or add it to the scope name to achieve consistency between scopes and claims.

**Comment by NEOAdvancedTechnology** [comment]
Group has no concerns.  Please make a PR.  Thanks!
