### ISSUE TITLE
Dynamic client registrations should include scopes

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-authorization#28]
See `scope` in https://tools.ietf.org/html/rfc7591#section-2

Client registration requests MUST include the scopes they may later request to be sure of being able to access what they need. It's only a MAY that auth servers can do this on a client's behalf. At present the spec and example request don't include this.

**Comment by lo-simon** [comment]
Is it mean Registry should never be performing dynamic registration as it does not need to have any scope assoicated to it, i.e. as it does not communicate with any protected APIs?

**Comment by andrewbonney** [comment]
I think it's true to say that a Registry doesn't need to perform registration as an OAuth client, but I think that's separate from this issue which is to make sure that Nodes and Controllers always do include a scope.
