### ISSUE TITLE
Keycloak auth server doesn't include 'client_id' in the access token by default

### ISSUE THREAD

**Issue by lo-simon** [AMWA-TV/nmos-authorization#34]
Keycloak auth server doen't not contain the _client_id_ in access token payload to conform with our spec.
see https://amwa-tv.github.io/nmos-authorization/branches/v1.0-dev/docs/4.4._Behaviour_-_Access_Tokens.html#client_id

**Comment by andrewbonney** [comment]
Noted. I'll investigate whether this can be enabled as it is useful for audit logging aside from anything else.

**Comment by NEOAdvancedTechnology** [comment]
Actively being looked into
