### ISSUE TITLE
Response code for incorrect/insufficient private claim

### ISSUE THREAD

**Issue by lo-simon** [AMWA-TV/nmos-authorization#49]
Regarding on what error code should be used if incorrect/insufficient private claim is used.  Should it be 401 (Unauthorized), or 403 (Forbidden)?

Based on https://tools.ietf.org/html/rfc6750#section-3.1, we guess it maybe 403? Any opinion?

Maybe this should be clarified in the specification.

    3.1.  Error Codes

    When a request fails, the resource server responds using the
    appropriate HTTP status code (typically, 400, 401, 403, or 405) and
    includes one of the following error codes in the response:
    invalid_request
          The request is missing a required parameter, includes an
          unsupported parameter or parameter value, repeats the same
          parameter, uses more than one method for including an access
          token, or is otherwise malformed.  The resource server SHOULD
          respond with the HTTP 400 (Bad Request) status code.
    invalid_token
          The access token provided is expired, revoked, malformed, or
          invalid for other reasons.  The resource SHOULD respond with
          the HTTP 401 (Unauthorized) status code.  The client MAY
          request a new access token and retry the protected resource
          request.
    insufficient_scope
          The request requires higher privileges than provided by the
          access token.  The resource server SHOULD respond with the HTTP
          403 (Forbidden) status code and MAY include the "scope"
          attribute with the scope necessary to access the protected
          resource.

    If the request lacks any authentication information (e.g., the client
    was unaware that authentication is necessary or attempted using an
    unsupported authentication method), the resource server SHOULD NOT
    include an error code or other error information.

    For example:
      HTTP/1.1 401 Unauthorized
      WWW-Authenticate: Bearer realm="example"

**Chris McArthur (Matrox)**
That is a very good question, I am under the impression a 403 would be the best respone
"We are extending the scope definition with a path permission in our private claims"

**Comment by garethsb-sony** [comment]
Will be resolved by #51.
