### ISSUE TITLE
API Interaction Sequence Diagram

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-authorization#53]
Reviewing the latest version of the diagram, I noticed the "User Agent" also mentions "Broadcast Control System" for that role.

![img](https://amwa-tv.github.io/nmos-authorization/branches/v1.0-dev/docs/images/authorization_flow.png)

This seems to be causing some confusion with the NMOS Controller in the network. Would it be possible to clarify the roles?
For most Nodes the "User Agent" will be a browser, perhaps mentioning that would help.

**Comment by garethsb** [comment]
Agreed - it's a good diagram apart from that parenthetical Broadcast Control System; I also thought in the case of a Node with no user interface, authentication via a *user-agent* that should be trusted by the *resource owner* (such as a browser) seems likely.

However, the description in [Overview - Client Types](https://github.com/AMWA-TV/nmos-authorization/blob/v1.0-dev/docs/1.0.%20Overview.md#client-types-informative) says a Node most resembles a *web application* with 'client credentials stored in a server', which is a *confidential client*. In that case, can there be no user-agent (or it could be considered a part of the client)?

**Comment by NEOAdvancedTechnology** [comment]
done
