### ISSUE TITLE
Spelling of authorization and source of diagrams?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-authorization#54]
I noticed one instance of 'authorisation' rather than 'authorization' in the text - in **2.0. APIs.md**.

There are several instances of it in the three diagrams. However, they are PNGs... I tried loading them into **draw.io** to see if the files had embedded editable objects, but that didn't seem to be the case.
I think it would be better to have editable diagrams in the repo?

**Comment by NEOAdvancedTechnology** [comment]
Thomas will take it as a project to do proper "authorization" of the document.

**Comment by NEOAdvancedTechnology** [comment]
```
grep -r -i authorisation nmos-authorization-1.0-dev     
nmos-authorization-1.0-dev/docs/2.0. APIs.md:*   **/register** - Used for the manual or dynamic registration of an OAuth 2.0 client with the Authorisation

grep -r -i authorise nmos-authorization-1.0-dev 
nmos-authorization-1.0-dev/docs/1.0. Overview.md:is not concerned with the security of the connection used to carry out authorization or subsequently authorised
```

**Comment by NEOAdvancedTechnology** [comment]
Who has the original sources for these images? 

![authorization_flow_language](https://user-images.githubusercontent.com/4744083/91894210-30484880-ec4a-11ea-8dad-a8198f6dcbde.png)
![nmos_sec_3_language](https://user-images.githubusercontent.com/4744083/91894219-32aaa280-ec4a-11ea-8bc5-50438e6336ba.png)

**Comment by prince-chrismc** [comment]
According to the slack you should be able to import them into draw.io and edit them there

**Comment by NEOAdvancedTechnology** [comment]
Giving draw.io a shot...

**Comment by NEOAdvancedTechnology** [comment]
Edited one diagram in draw.io, re-drew the other in draw.io
