### ISSUE TITLE
[dannym-refactor] auth_metadata.json

### ISSUE THREAD

**Issue by lo-simon** [AMWA-TV/nmos-authorization#6]
I think 'token_endpoint' should also be form part of the required elements in the auth_metadata.json scheme.

`
"required": ["issuer", "authorization_endpoint", "jwks_uri", "registration_endpoint", "revocation_endpoint", "response_types_supported"]
`
to
`
"required": ["issuer", "authorization_endpoint", "token_endpoint", "jwks_uri", "registration_endpoint", "revocation_endpoint", "response_types_supported"]
`

**Comment by garethsb** [comment]
Yes, and the `description`s probably need updating so that the `"required"` list corresponds to the use of REQUIRED, etc. in the descriptions?

**Comment by NEOAdvancedTechnology** [comment]
worked out
