### ISSUE TITLE
[dannym-refactor] Schemas aren't valid JSON due to multi-line strings!

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-authorization#7]
E.g. https://github.com/AMWA-TV/nmos-authorization/blob/dannym-refactor/APIs/schemas/jwks_response.json and https://github.com/AMWA-TV/nmos-authorization/blob/dannym-refactor/APIs/schemas/auth_metadata.json currently contain multi-line strings, which aren't valid. If new-lines are actually required in the descriptions they should be encoded as e.g. `\n`.

**Comment by NEOAdvancedTechnology** [comment]
solved
