### ISSUE TITLE
Are clients using PKCE required to support "S256" or not?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-authorization#73]
https://github.com/AMWA-TV/nmos-authorization/blob/v1.0-dev/docs/4.3.%20Behaviour%20-%20Token%20Requests.md#grants says:

> When using PKCE, clients MUST support and prefer the "S256" `code_challenge_method`.

But below, in https://github.com/AMWA-TV/nmos-authorization/blob/v1.0-dev/docs/4.3.%20Behaviour%20-%20Token%20Requests.md#authorization-request-and-response it says:

> A `code_challenge_method` parameter MUST be used alongside the `code_challenge` parameter and SHOULD be equal to "S256" unless the client is unable to perform a SHA256 hash, in which case a value of "plain" MAY be used.

If _clients_ are permitted to use "plain", should we make explicit somewhere that _servers_ MUST support both "S256" and "plain"? And update the examples, some of which only have "S256" in the array.

**Comment by peterbrightwell** [comment]
@garethsb-sony yes. @andrewbonney will do a PR
