### ISSUE TITLE
Client Name Duplications

### ISSUE THREAD

**Issue by dannymeloy** [AMWA-TV/nmos-authorization#78]
When using [Dynamic Client Registration](https://tools.ietf.org/html/rfc7591), should the "Client Name" format be defined in order to prevent duplicate client names within the auth server? It would also provide a meaning to client names (where client IDs and client secrets are usually just random strings) and would provide a deterministic format for potential automation?

The client name could simply be the FQDN of the device, if the device is unlikely to change hostname. Perhaps in a more dynamic scenario where devices are likely to change domain it could perhaps be a concatenation of the product name with their MAC address to prevent registering multiple clients per device.

**Comment by peterbrightwell** [comment]
Discussed on call. Will become more important once #76 is known.   What about @dannymeloy suggestions?

**Comment by peterbrightwell** [comment]
Closed following approval of #77
