### ISSUE TITLE
Clarify the resource server behaviour while receiving missing public keys token

### ISSUE THREAD

**Issue by lo-simon** [AMWA-TV/nmos-authorization#84]
Let start with the following actors, 2 Authorization Servers, A and B. 
A NMOS Node which is a resource server (serving the node and connection APIs) and a client (accessing the registration API).

- Node is registered to Authorization Server A and polling it for tokens and public keys.
- Authorization Server A does not contain Authorization Server B public keys.
- Some service try to access Node API with Authorization Server B token.
- Node should....

Following are the examples of how the Node could handing in this situation:

**Idea 1**
1. Return 503 with a Retry-After value.
2. Using the Token B Issuer (Authorization Server B) to fetch the authorization server metadata.
3. Check has the Node already registered in Authorization Server B, need to somehow obtain the relevant registered client metadata associated with Authorization Server B, maybe from a database.
4. If the relevant client metadata found.
5. Using the client metadata to fetch the up-to-date client metadata from the Authorization Server B, if it is an OpenID Connect server.
6. If relevant client metadata not found, or no client metdadata is retruned from the OpenID Connect server. Perform Node registration to Authorization Server B. Token will need to be authorized, i.e. user interaction required (not good!, as it could happen at anytime, and you may have no-one there to authorize it).
7. Continuously to fetch Public Keys and Tokens from Authorization Server B in time interval.
8. Above steps could happen again, in event of receiving token from Authorization Server A, and so on...

**Idea 2**
1. Return 503 with a Retry-After value.
2. Using the Token B Issuer (Authorization Server B) to fetch the authorization server metadata.
3. Fetch the public keys from Authorization Server B.
4. Append any missing keys (from Authorization Server B) to the public keys cache (from Authorization Server A).
5. When time to re-fetch the public keys from Authorization A, Authorization B public keys are discarded.
6. Above steps could happen again, in event of receiving the token from Authorization Server B, and so on...

**Idea 3**
Maybe the best solution would be updating the spec (Servers.md) using the word MUST instead of SHOULD in the following statement.
"Where multiple Authorization Servers exist in a single deployment SHOULD each host a copy of each other's public keys in order to prevent Resource Servers having to make requests to every instance."
Then Node will never received a token with missing public keys in either of the Authorization Servers.  The only time Node does not has the public keys, could at the startup because it has not fetched the public keys yet. Node then return 503, and trigger to logon to the Token Issuer Server is okay.

_Can anyone else think of any other idea?_

After writing up the above cases I have another question, is it really a good idea to support multi-authorization servers?  Let say you connected to Authorization Server A, token is authorized, user interaction.  Sometime later, some network issue, or Server A is disconnected, Node is switched over to Server B, but that will again require token authorization, user interaction, and that could happen while no-one can authorize it...  This is another use case for allowing client credentials flow instead of authorization code flow, for any devices or systems running 24/7.

**Comment by prince-chrismc** [comment]
> After writing up the above cases I have another question, is it really a good idea to support multi-authorization servers?

The workflow I've always imagined when talking about this is... When you have multiple physical location, you typically have a on-cloud authorization system for the company. At each location, in it's media network, 90% of the equipment is local so it has it's own dedicated authorization server (to minimize breaches). It's easy to imagine with COVID, someone working remote or off-site may still needs to control that machine. That employee using their on-cloud user account and token tries to access the media node.

Replicated the private keys on two servers doubles the risk of them being exposed, I am not convinced that should be a MUST. It make the system more interoperable when they are the same which is the SHOULD.

---

To try to answer the main question...

I think your _Idea 2_, matches closest with my understanding of the spec. https://github.com/AMWA-TV/nmos-authorization/blob/v1.0-dev/docs/4.5.%20Behaviour%20-%20Resource%20Servers.md#public-keys 

> Where a Resource Server has no matching public key [...] attempt to obtain the missing public key via the the token iss claim [...] where the Resource Server needs to fetch a public key [...] MAY temporarily respond with an HTTP 503 code [...] SHOULD include an HTTP Retry-After header to indicate when the client may retry its request.

This was the consensus from #57 Do you see any improvements that we can make?

🤔 I think these steps are an implementation detail. 

> 4. Append any missing keys (from Authorization Server B) to the public keys cache (from Authorization Server A).
> 5. When time to re-fetch the public keys from Authorization A, Authorization B public keys are discarded.
> 6. Above steps could happen again, in event of receiving the token from Authorization Server B, and so on...

How you manage the cache is out side the scope of the spec? 💭  I would have expected a map of `iss` to `JWKs`, this way you don't need to invalidate the entire cache or use keys that are not relevant.

**Comment by lo-simon** [comment]
> The workflow I've always imagined when talking about this is... When you have multiple physical location, you typically have a on-cloud authorization system for the company. At each location, in it's media network, 90% of the equipment is local so it has it's own dedicated authorization server (to minimize breaches). It's easy to imagine with COVID, someone working remote or off-site may still needs to control that machine. That employee using their on-cloud user account and token tries to access the media node.
>
>Replicated the private keys on two servers doubles the risk of them being exposed, I am not convinced that should be a MUST. It make the system more interoperable when they are the same which is the SHOULD.

And looking back to #57, Andrew and you have convinced me that, using SHOULD is correct.

> How you manage the cache is out side the scope of the spec? 💭 I would have expected a map of iss to JWKs, this way you don't need to invalidate the entire cache or use keys that are not relevant.

Thanks for your suggestion, I always look into the imlementation, using map of iss to JWKs fit `Ideal 2` nicely.

**Comment by peterbrightwell** [comment]
Discussed on call. We are in agreement with the suggestion. TBD: where best to provide this information?  E.g. Wiki or whatever comes next.

**Comment by peterbrightwell** [comment]
Covered in INFO-002
