### ISSUE TITLE
[dannym-refactor] Relationship between DNS-SD discovery and RFC 8414 approach

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-authorization#9]
Discovery mechanism currently defined uses DNS-SD via service type **_nmos-auth._tcp**. With the TXT records defined this allows URLs to be constructed of the form **{proto}://{host}:{port}/x-nmos/auth/{version}**. (There may be multiple such URLs for one DNS-SD service instance if multiple protocols or API versions are advertised.)

With the proposed alignment to RFC 8414, will BCP-003-02 recommend the above approach to discovering an auth server, or does the RFC 8414 **/.well-known/** URL come into play? That URL isn't versioned, so I'm not sure how these specs should play nicely together.

**Comment by NEOAdvancedTechnology** [comment]
worked out
