### ISSUE TITLE
Implementation guide for Node vendors

### ISSUE THREAD

**Issue by firthmj** [AMWA-TV/nmos-authorization#97]
Reading BCP-003-02 and IS-10 is very hard going for someone who is not already well versed in web security technologies (OAuth2 / JWT etc)

Understanding what areas of the IS-10/BCP-003-02 and the referenced IETF specs are needed by a node vendor (I think it is a relatively small subset), and a "quick start" guide to those areas would be very useful.

More examples of the interactions for a node would also be good.

**Comment by peterbrightwell** [comment]
Covered by new INFO-002 https://specs.amwa.tv/info-002 and https://github.com/AMWA-TV/nmos-authorization-implementation-guide
