### ISSUE TITLE
Interaction diagram needs updating

### ISSUE THREAD

**Issue by peterbrightwell** [AMWA-TV/nmos-authorization#99]
API Interaction sequence diagram in 2.0. APIs.md precedes recent client credentials grant and should be updated, probably with node and controller diagrams.

**Comment by andrewbonney** [comment]
Danny noted that this may simply need a reference updating given https://github.com/AMWA-TV/nmos-authorization/blob/v1.0-dev/docs/images/client_credentials_flow.png exists
